// Code generated by godddx.
package taskdb

import (
	"github.com/ixugo/vdub/internal/core/task"
	"gorm.io/gorm"
)

var _ task.Storer = DB{}

// DB Related business namespaces
type DB struct {
	db *gorm.DB
}

// NewDB instance object
func NewDB(db *gorm.DB) DB {
	return DB{db: db}
}

// Task Get business instance
func (d DB) Task() task.TaskStorer {
	return Task(d)
}

// Step Get business instance
func (d DB) Step() task.StepStorer {
	return Step(d)
}

// AutoMigrate sync database
func (d DB) AutoMigrate(ok bool) DB {
	if !ok {
		return d
	}
	if err := d.db.AutoMigrate(
		new(task.Task),
		new(task.Step),
	); err != nil {
		panic(err)
	}
	return d
}
