// Code generated by godddx.
package taskdb

import (
	"context"

	"github.com/ixugo/goddd/pkg/orm"
	"github.com/ixugo/vdub/internal/core/task"
	"gorm.io/gorm"
)

var _ task.StepStorer = Step{}

// Step Related business namespaces
type Step DB

// NewStep instance object
func NewStep(db *gorm.DB) Step {
	return Step{db: db}
}

// List implements task.StepStorer.
func (d Step) List(ctx context.Context, bs *[]*task.Step, page orm.Pager, opts ...orm.QueryOption) (int64, error) {
	return orm.ListWithContext(ctx, d.db, bs, page, opts...)
}

// Get implements task.StepStorer.
func (d Step) Get(ctx context.Context, model *task.Step, opts ...orm.QueryOption) error {
	return orm.FirstWithContext(ctx, d.db, model, opts...)
}

// Create implements task.StepStorer.
func (d Step) Create(ctx context.Context, model *task.Step) error {
	return d.db.WithContext(ctx).Create(model).Error
}

// Update implements task.StepStorer.
func (d Step) Update(ctx context.Context, model *task.Step, changeFn func(*task.Step), opts ...orm.QueryOption) error {
	return orm.UpdateWithContext(ctx, d.db, model, changeFn, opts...)
}

// Del implements task.StepStorer.
func (d Step) Delete(ctx context.Context, model *task.Step, opts ...orm.QueryOption) error {
	return orm.DeleteWithContext(ctx, d.db, model, opts...)
}

// Count implements task.StepStorer.
func (d Step) Count(ctx context.Context, opts ...orm.QueryOption) (int64, error) {
	return orm.CountWithContext[task.Step](ctx, d.db, opts...)
}

// Session 事务组合
func (d Step) Session(ctx context.Context, changeFns ...func(*gorm.DB) error) error {
	return d.db.WithContext(ctx).Transaction(func(tx *gorm.DB) error {
		for _, fn := range changeFns {
			if err := fn(tx); err != nil {
				return err
			}
		}
		return nil
	})
}

// UpdateWithSession 修改事务
func (d Step) UpdateWithSession(tx *gorm.DB, model *task.Step, changeFn func(b *task.Step) error, opts ...orm.QueryOption) error {
	return orm.UpdateWithSession(tx, model, changeFn, opts...)
}
