// Code generated by godddx.
package taskdb

import (
	"context"

	"github.com/ixugo/goddd/pkg/orm"
	"github.com/ixugo/vdub/internal/core/task"
	"gorm.io/gorm"
)

var _ task.TaskLogStorer = TaskLog{}

// TaskLog Related business namespaces
type TaskLog DB

// NewTaskLog instance object
func NewTaskLog(db *gorm.DB) TaskLog {
	return TaskLog{db: db}
}

// List implements task.TaskLogStorer.
func (d TaskLog) List(ctx context.Context, bs *[]*task.TaskLog, page orm.Pager, opts ...orm.QueryOption) (int64, error) {
	return orm.ListWithContext(ctx, d.db, bs, page, opts...)
}

// Get implements task.TaskLogStorer.
func (d TaskLog) Get(ctx context.Context, model *task.TaskLog, opts ...orm.QueryOption) error {
	return orm.FirstWithContext(ctx, d.db, model, opts...)
}

// Create implements task.TaskLogStorer.
func (d TaskLog) Create(ctx context.Context, model *task.TaskLog) error {
	return d.db.WithContext(ctx).Create(model).Error
}

// Update implements task.TaskLogStorer.
func (d TaskLog) Update(ctx context.Context, model *task.TaskLog, changeFn func(*task.TaskLog), opts ...orm.QueryOption) error {
	return orm.UpdateWithContext(ctx, d.db, model, changeFn, opts...)
}

// Del implements task.TaskLogStorer.
func (d TaskLog) Delete(ctx context.Context, model *task.TaskLog, opts ...orm.QueryOption) error {
	return orm.DeleteWithContext(ctx, d.db, model, opts...)
}

// Count implements task.TaskLogStorer.
func (d TaskLog) Count(ctx context.Context, opts ...orm.QueryOption) (int64, error) {
	return orm.CountWithContext[task.TaskLog](ctx, d.db, opts...)
}

// Append 在同一事务中写入日志并裁掉超出上限的最旧记录。
func (d TaskLog) Append(ctx context.Context, model *task.TaskLog, maxLines int) error {
	return d.db.WithContext(ctx).Transaction(func(tx *gorm.DB) error {
		if err := tx.Create(model).Error; err != nil {
			return err
		}
		var expiredIDs []int64
		if err := tx.Model(new(task.TaskLog)).
			Where("task_id = ?", model.TaskID).
			Order("id DESC").
			Offset(maxLines).
			Pluck("id", &expiredIDs).Error; err != nil {
			return err
		}
		if len(expiredIDs) == 0 {
			return nil
		}
		return tx.Where("id IN ?", expiredIDs).Delete(new(task.TaskLog)).Error
	})
}

// ListRecent 先取最新记录，再反转为界面所需的时间正序。
func (d TaskLog) ListRecent(ctx context.Context, taskID string, limit int) ([]*task.TaskLog, error) {
	items := make([]*task.TaskLog, 0, limit)
	err := d.db.WithContext(ctx).
		Where("task_id = ?", taskID).
		Order("id DESC").
		Limit(limit).
		Find(&items).Error
	if err != nil {
		return nil, err
	}
	for left, right := 0, len(items)-1; left < right; left, right = left+1, right-1 {
		items[left], items[right] = items[right], items[left]
	}
	return items, nil
}

// Session 事务组合
func (d TaskLog) Session(ctx context.Context, changeFns ...func(*gorm.DB) error) error {
	return d.db.WithContext(ctx).Transaction(func(tx *gorm.DB) error {
		for _, fn := range changeFns {
			if err := fn(tx); err != nil {
				return err
			}
		}
		return nil
	})
}

// UpdateWithSession 修改事务
func (d TaskLog) UpdateWithSession(tx *gorm.DB, model *task.TaskLog, changeFn func(b *task.TaskLog) error, opts ...orm.QueryOption) error {
	return orm.UpdateWithSession(tx, model, changeFn, opts...)
}
