// Code generated by godddx.
package taskdb

import (
	"context"

	"github.com/ixugo/goddd/pkg/orm"
	"github.com/ixugo/vdub/internal/core/task"
	"gorm.io/gorm"
)

var _ task.TaskStorer = Task{}

// Task Related business namespaces
type Task DB

// NewTask instance object
func NewTask(db *gorm.DB) Task {
	return Task{db: db}
}

// List implements task.TaskStorer.
func (d Task) List(ctx context.Context, bs *[]*task.Task, page orm.Pager, opts ...orm.QueryOption) (int64, error) {
	return orm.ListWithContext(ctx, d.db, bs, page, opts...)
}

// Get implements task.TaskStorer.
func (d Task) Get(ctx context.Context, model *task.Task, opts ...orm.QueryOption) error {
	return orm.FirstWithContext(ctx, d.db, model, opts...)
}

// Create implements task.TaskStorer.
func (d Task) Create(ctx context.Context, model *task.Task) error {
	return d.db.WithContext(ctx).Create(model).Error
}

// Update implements task.TaskStorer.
func (d Task) Update(ctx context.Context, model *task.Task, changeFn func(*task.Task), opts ...orm.QueryOption) error {
	return orm.UpdateWithContext(ctx, d.db, model, changeFn, opts...)
}

// Del implements task.TaskStorer.
func (d Task) Delete(ctx context.Context, model *task.Task, opts ...orm.QueryOption) error {
	return orm.DeleteWithContext(ctx, d.db, model, opts...)
}

// Count implements task.TaskStorer.
func (d Task) Count(ctx context.Context, opts ...orm.QueryOption) (int64, error) {
	return orm.CountWithContext[task.Task](ctx, d.db, opts...)
}

// Session 事务组合
func (d Task) Session(ctx context.Context, changeFns ...func(*gorm.DB) error) error {
	return d.db.WithContext(ctx).Transaction(func(tx *gorm.DB) error {
		for _, fn := range changeFns {
			if err := fn(tx); err != nil {
				return err
			}
		}
		return nil
	})
}

// UpdateWithSession 修改事务
func (d Task) UpdateWithSession(tx *gorm.DB, model *task.Task, changeFn func(b *task.Task) error, opts ...orm.QueryOption) error {
	return orm.UpdateWithSession(tx, model, changeFn, opts...)
}
