// Code generated by godddx.
package task

// Storer data persistence
type Storer interface {
	Task() TaskStorer
	Step() StepStorer
}

// Core business domain
type Core struct {
	store Storer
}

// NewCore create business domain
func NewCore(store Storer) Core {
	return Core{store: store}
}
