// Code generated by godddx.
package task

import (
	"context"
	"log/slog"

	"github.com/ixugo/goddd/pkg/orm"
	"github.com/ixugo/goddd/pkg/reason"
	"github.com/jinzhu/copier"
	"gorm.io/gorm"
)

// StepStorer Instantiation interface
type StepStorer interface {
	List(context.Context, *[]*Step, orm.Pager, ...orm.QueryOption) (int64, error)
	Get(context.Context, *Step, ...orm.QueryOption) error
	Create(context.Context, *Step) error
	Update(context.Context, *Step, func(*Step), ...orm.QueryOption) error
	Delete(context.Context, *Step, ...orm.QueryOption) error
	Count(context.Context, ...orm.QueryOption) (int64, error)

	Session(context.Context, ...func(*gorm.DB) error) error
	UpdateWithSession(*gorm.DB, *Step, func(b *Step) error, ...orm.QueryOption) error
}

// ListStep Paginated search
func (c Core) ListSteps(ctx context.Context, in *ListStepInput) ([]*Step, int64, error) {
	query := in.ToQuery()

	items := make([]*Step, 0, in.Limit())
	total, err := c.store.Step().List(ctx, &items, in, query.Encode()...)
	if err != nil {
		return nil, 0, reason.ErrDB.Withf(`List in[%+v] err[%s]`, in, err.Error())
	}
	return items, total, nil
}

// GetStep Query a single object
func (c Core) GetStep(ctx context.Context, id string) (*Step, error) {
	// 提前赋值是为了缓存
	out := Step{ID: id}
	if err := c.store.Step().Get(ctx, &out, orm.Where("id=?", id)); err != nil {
		if orm.IsErrRecordNotFound(err) {
			return nil, reason.ErrNotFound.Withf(`Get id[%v] err[%s]`, id, err.Error())
		}
		return nil, reason.ErrDB.Withf(`Get id[%v] err[%s]`, id, err.Error())
	}
	return &out, nil
}

// CreateStep Insert into database
func (c Core) CreateStep(ctx context.Context, in *CreateStepInput) (*Step, error) {
	var out Step
	if err := copier.Copy(&out, in); err != nil {
		slog.ErrorContext(ctx, "Copy", "err", err)
	}

	if err := c.store.Step().Create(ctx, &out); err != nil {
		return nil, reason.ErrDB.Withf(`Create err[%s]`, err.Error())
	}
	return &out, nil
}

// UpdateStep Update object information
func (c Core) UpdateStep(ctx context.Context, in *UpdateStepInput, id string) (*Step, error) {
	var out Step
	if err := c.store.Step().Update(ctx, &out, func(b *Step) {
		if err := copier.Copy(b, in); err != nil {
			slog.ErrorContext(ctx, "Copy", "err", err)
		}
	}, orm.Where("id=?", id)); err != nil {
		return nil, reason.ErrDB.Withf(`Update id[%v] err[%s]`, id, err.Error())
	}
	return &out, nil
}

// DeleteStep Delete object
func (c Core) DeleteStep(ctx context.Context, id string) (*Step, error) {
	var out Step
	if err := c.store.Step().Delete(ctx, &out, orm.Where("id=?", id)); err != nil {
		return nil, reason.ErrDB.Withf(`Del id[%v] err[%s]`, id, err.Error())
	}
	return &out, nil
}
