// Code generated by godddx.
package task

import (
	"context"
	"crypto/sha1"
	"fmt"
	"log/slog"

	"github.com/ixugo/goddd/pkg/orm"
	"github.com/ixugo/goddd/pkg/reason"
	"github.com/jinzhu/copier"
	"gorm.io/gorm"
)

// StepStorer Instantiation interface
type StepStorer interface {
	List(context.Context, *[]*Step, orm.Pager, ...orm.QueryOption) (int64, error)
	Get(context.Context, *Step, ...orm.QueryOption) error
	Create(context.Context, *Step) error
	Update(context.Context, *Step, func(*Step), ...orm.QueryOption) error
	Delete(context.Context, *Step, ...orm.QueryOption) error
	Count(context.Context, ...orm.QueryOption) (int64, error)

	Session(context.Context, ...func(*gorm.DB) error) error
	UpdateWithSession(*gorm.DB, *Step, func(b *Step) error, ...orm.QueryOption) error
}

// ListStep Paginated search
func (c Core) ListSteps(ctx context.Context, in *ListStepInput) ([]*Step, int64, error) {
	query := in.ToQuery()

	items := make([]*Step, 0, in.Limit())
	total, err := c.store.Step().List(ctx, &items, in, query.Encode()...)
	if err != nil {
		return nil, 0, reason.ErrDB.Withf(`List in[%+v] err[%s]`, in, err.Error())
	}
	return items, total, nil
}

// GetStep Query a single object
func (c Core) GetStep(ctx context.Context, id string) (*Step, error) {
	// 提前赋值是为了缓存
	out := Step{ID: id}
	if err := c.store.Step().Get(ctx, &out, orm.Where("id=?", id)); err != nil {
		if orm.IsErrRecordNotFound(err) {
			return nil, reason.ErrNotFound.Withf(`Get id[%v] err[%s]`, id, err.Error())
		}
		return nil, reason.ErrDB.Withf(`Get id[%v] err[%s]`, id, err.Error())
	}
	return &out, nil
}

// CreateStep Insert into database
func (c Core) CreateStep(ctx context.Context, in *CreateStepInput) (*Step, error) {
	var out Step
	if err := copier.Copy(&out, in); err != nil {
		slog.ErrorContext(ctx, "Copy", "err", err)
	}

	if err := c.store.Step().Create(ctx, &out); err != nil {
		return nil, reason.ErrDB.Withf(`Create err[%s]`, err.Error())
	}
	return &out, nil
}

// UpdateStep Update object information
func (c Core) UpdateStep(ctx context.Context, in *UpdateStepInput, id string) (*Step, error) {
	var out Step
	if err := c.store.Step().Update(ctx, &out, func(b *Step) {
		if err := copier.Copy(b, in); err != nil {
			slog.ErrorContext(ctx, "Copy", "err", err)
		}
	}, orm.Where("id=?", id)); err != nil {
		return nil, reason.ErrDB.Withf(`Update id[%v] err[%s]`, id, err.Error())
	}
	return &out, nil
}

// DeleteStep Delete object
func (c Core) DeleteStep(ctx context.Context, id string) (*Step, error) {
	var out Step
	if err := c.store.Step().Delete(ctx, &out, orm.Where("id=?", id)); err != nil {
		return nil, reason.ErrDB.Withf(`Del id[%v] err[%s]`, id, err.Error())
	}
	return &out, nil
}

// UpsertStep 按任务和步骤生成稳定 ID，使重试与断点恢复更新同一条记录。
func (c Core) UpsertStep(
	ctx context.Context,
	taskID string,
	name string,
	changeFn func(*Step),
) error {
	id := uuidV5([]byte(taskID + "/" + name))
	current := Step{ID: id}
	err := c.store.Step().Get(ctx, &current, orm.Where("id=?", id))
	if err == nil {
		return c.store.Step().Update(ctx, &current, changeFn, orm.Where("id=?", id))
	}
	if !orm.IsErrRecordNotFound(err) {
		return reason.ErrDB.Withf("GetStep task_id[%s] name[%s] err[%s]", taskID, name, err.Error())
	}
	current = Step{ID: id, TaskID: taskID, Name: name}
	changeFn(&current)
	if err := c.store.Step().Create(ctx, &current); err != nil {
		return reason.ErrDB.Withf("CreateStep task_id[%s] name[%s] err[%s]", taskID, name, err.Error())
	}
	return nil
}

// namespaceOID 是 RFC 4122 OID 命名空间，与 google/uuid.NameSpaceOID 相同。
var namespaceOID = [16]byte{0x6b, 0xa7, 0xb8, 0x12, 0x9d, 0xad, 0x11, 0xd1, 0x80, 0xb4, 0x00, 0xc0, 0x4f, 0xd4, 0x30, 0xc8}

// uuidV5 生成 UUID v5（SHA-1），与 uuid.NewSHA1(uuid.NameSpaceOID, name) 输出一致。
func uuidV5(name []byte) string {
	h := sha1.New()
	h.Write(namespaceOID[:])
	h.Write(name)
	s := h.Sum(nil)
	s[6] = (s[6] & 0x0f) | 0x50
	s[8] = (s[8] & 0x3f) | 0x80
	return fmt.Sprintf("%x-%x-%x-%x-%x", s[0:4], s[4:6], s[6:8], s[8:10], s[10:16])
}
