// Code generated by godddx.
package task

import (
	"time"

	"github.com/ixugo/goddd/pkg/orm"
	"github.com/ixugo/vdub/pkg/web"
)

type ListStepInput struct {
	web.PagerFilter
	TaskID    string     `form:"task_id"`
	Name      string     `form:"name"`   // whisper/split/translate/tts/merge/burn
	Status    int        `form:"status"` // 0=待执行, 1=执行中, 2=完成, 3=失败, 4=跳过
	Progress  int        `form:"progress"`
	Detail    string     `form:"detail"`
	Output    string     `form:"output"` // JSON: 步骤输出（中间产物路径等）
	Error     string     `form:"error"`
	StartedAt *time.Time `form:"started_at"`
	EndedAt   *time.Time `form:"ended_at"`
}

// ToQuery 按任务与步骤名称筛选，保证详情页只读取当前任务的处理记录。
func (i *ListStepInput) ToQuery() *orm.Query {
	query := orm.NewQuery(2)
	if i.TaskID != "" {
		query.Where("task_id = ?", i.TaskID)
	}
	if i.Name != "" {
		query.Where("name = ?", i.Name)
	}
	return query.OrderBy("created_at ASC")
}

type UpdateStepInput struct {
	ID        string     `uri:"id"`
	TaskID    string     `json:"task_id"`
	Name      string     `json:"name"`   // whisper/split/translate/tts/merge/burn
	Status    int        `json:"status"` // 0=待执行, 1=执行中, 2=完成, 3=失败, 4=跳过
	Progress  int        `json:"progress"`
	Detail    string     `json:"detail"`
	Output    string     `json:"output"` // JSON: 步骤输出（中间产物路径等）
	Error     string     `json:"error"`
	StartedAt *time.Time `json:"started_at"`
	EndedAt   *time.Time `json:"ended_at"`
}

type CreateStepInput struct {
	TaskID    string     `json:"task_id"`
	Name      string     `json:"name"`   // whisper/split/translate/tts/merge/burn
	Status    int        `json:"status"` // 0=待执行, 1=执行中, 2=完成, 3=失败, 4=跳过
	Progress  int        `json:"progress"`
	Detail    string     `json:"detail"`
	Output    string     `json:"output"` // JSON: 步骤输出（中间产物路径等）
	Error     string     `json:"error"`
	StartedAt *time.Time `json:"started_at"`
	EndedAt   *time.Time `json:"ended_at"`
}

type GetStepInput struct {
	ID string `uri:"id"`
}

type DeleteStepInput struct {
	ID string `uri:"id"`
}
