// Code generated by godddx.
package task

import "time"

// Step domain model
type Step struct {
	ID        string     `gorm:"primaryKey" json:"id"`
	TaskID    string     `gorm:"column:task_id;notNull;default:''" json:"task_id"`
	Name      string     `gorm:"column:name;notNull;default:'';comment:whisper/split/translate/tts/merge/burn" json:"name"` // whisper/split/translate/tts/merge/burn
	Status    int        `gorm:"column:status;notNull;default:0;comment:0=待执行, 1=执行中, 2=完成, 3=失败, 4=跳过" json:"status"`      // 0=待执行, 1=执行中, 2=完成, 3=失败, 4=跳过
	Output    string     `gorm:"column:output;notNull;default:'';comment:JSON: 步骤输出（中间产物路径等）" json:"output"`                // JSON: 步骤输出（中间产物路径等）
	Error     string     `gorm:"column:error;notNull;default:''" json:"error"`
	StartedAt *time.Time `gorm:"column:started_at" json:"started_at"`
	EndedAt   *time.Time `gorm:"column:ended_at" json:"ended_at"`
	CreatedAt time.Time  `gorm:"column:created_at;notNull;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt time.Time  `gorm:"column:updated_at;notNull;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName database table name
func (*Step) TableName() string {
	return "steps"
}

// CacheKey 缓存主键，必须唯一
// godddx 生成缓存代码时，依赖的主键
// 默认应该是 ID 字段，但也可以自定义
func (s *Step) CacheKey() string {
	return s.ID
}
