// Code generated by godddx.
package task

import (
	"context"
	"log/slog"
	"uuid"

	"github.com/ixugo/goddd/pkg/orm"
	"github.com/ixugo/goddd/pkg/reason"
	"github.com/jinzhu/copier"
	"gorm.io/gorm"
)

// TaskStorer Instantiation interface
type TaskStorer interface {
	List(context.Context, *[]*Task, orm.Pager, ...orm.QueryOption) (int64, error)
	Get(context.Context, *Task, ...orm.QueryOption) error
	Create(context.Context, *Task) error
	Update(context.Context, *Task, func(*Task), ...orm.QueryOption) error
	Delete(context.Context, *Task, ...orm.QueryOption) error
	Count(context.Context, ...orm.QueryOption) (int64, error)

	Session(context.Context, ...func(*gorm.DB) error) error
	UpdateWithSession(*gorm.DB, *Task, func(b *Task) error, ...orm.QueryOption) error
}

// ListTask Paginated search
func (c Core) ListTasks(ctx context.Context, in *ListTaskInput) ([]*Task, int64, error) {
	query := in.ToQuery()

	items := make([]*Task, 0, in.Limit())
	total, err := c.store.Task().List(ctx, &items, in, query.Encode()...)
	if err != nil {
		return nil, 0, reason.ErrDB.Withf(`List in[%+v] err[%s]`, in, err.Error())
	}
	for _, item := range items {
		enrichTaskFiles(item)
	}
	return items, total, nil
}

// GetTask Query a single object
func (c Core) GetTask(ctx context.Context, id string) (*Task, error) {
	// 提前赋值是为了缓存
	out := Task{ID: id}
	if err := c.store.Task().Get(ctx, &out, orm.Where("id=?", id)); err != nil {
		if orm.IsErrRecordNotFound(err) {
			return nil, reason.ErrNotFound.Withf(`Get id[%v] err[%s]`, id, err.Error())
		}
		return nil, reason.ErrDB.Withf(`Get id[%v] err[%s]`, id, err.Error())
	}
	enrichTaskFiles(&out)
	return &out, nil
}

// CreateTask Insert into database
func (c Core) CreateTask(ctx context.Context, in *CreateTaskInput) (*Task, error) {
	var out Task
	if err := copier.Copy(&out, in); err != nil {
		slog.ErrorContext(ctx, "Copy", "err", err)
	}
	if out.ID == "" {
		out.ID = uuid.New().String()
	}

	if err := c.store.Task().Create(ctx, &out); err != nil {
		return nil, reason.ErrDB.Withf(`Create err[%s]`, err.Error())
	}
	enrichTaskFiles(&out)
	return &out, nil
}

// SetTaskStatus 精确更新任务的指定字段，避免零值覆盖其它进度信息。
func (c Core) SetTaskStatus(ctx context.Context, id string, fn func(*Task)) error {
	var out Task
	if err := c.store.Task().Update(ctx, &out, fn, orm.Where("id=?", id)); err != nil {
		return reason.ErrDB.Withf("SetTaskStatus id[%v] err[%s]", id, err.Error())
	}
	return nil
}

// UpdateTask Update object information
func (c Core) UpdateTask(ctx context.Context, in *UpdateTaskInput, id string) (*Task, error) {
	var out Task
	if err := c.store.Task().Update(ctx, &out, func(b *Task) {
		if err := copier.Copy(b, in); err != nil {
			slog.ErrorContext(ctx, "Copy", "err", err)
		}
	}, orm.Where("id=?", id)); err != nil {
		return nil, reason.ErrDB.Withf(`Update id[%v] err[%s]`, id, err.Error())
	}
	enrichTaskFiles(&out)
	return &out, nil
}

// DeleteTask 先清理任务产物再删除记录，清理失败时保留记录供重试。
func (c Core) DeleteTask(ctx context.Context, id string) (*Task, error) {
	out := Task{ID: id}
	if err := c.store.Task().Get(ctx, &out, orm.Where("id=?", id)); err != nil {
		if orm.IsErrRecordNotFound(err) {
			return &out, nil
		}
		return nil, reason.ErrDB.Withf("读取待删除任务失败: %s", err)
	}
	if err := c.removeTaskFiles(ctx, &out); err != nil {
		slog.ErrorContext(ctx, "删除任务产物失败", "task_id", id, "err", err)
		return nil, err
	}
	if err := c.store.Task().Delete(ctx, &out, orm.Where("id=?", id)); err != nil {
		return nil, reason.ErrDB.Withf(`Del id[%v] err[%s]`, id, err.Error())
	}
	slog.InfoContext(ctx, "任务及产物已删除", "task_id", id)
	return &out, nil
}
