// Code generated by godddx.
package task

import (
	"github.com/ixugo/goddd/pkg/orm"
	"github.com/ixugo/goddd/pkg/web"
)

type ListTaskInput struct {
	web.PagerFilter
	InputPath   string `form:"input_path"`
	OutputDir   string `form:"output_dir"`
	Mode        int    `form:"mode"`   // 1=仅字幕, 2=字幕+翻译, 3=字幕+翻译+配音
	Status      int    `form:"status"` // 0=待处理, 1=进行中, 2=已暂停, 3=已完成, 4=失败
	CurrentStep string `form:"current_step"`
	Progress    int    `form:"progress"`
	Error       string `form:"error"`
	TargetLang  string `form:"target_lang"`
}

func (i *ListTaskInput) ToQuery() *orm.Query {
	// TODO: 实现 ToQuery 条件
	return orm.NewQuery(1).OrderBy("created_at DESC")
}

type UpdateTaskInput struct {
	ID          string `uri:"id"`
	InputPath   string `json:"input_path"`
	OutputDir   string `json:"output_dir"`
	Mode        int    `json:"mode"`   // 1=仅字幕, 2=字幕+翻译, 3=字幕+翻译+配音
	Status      int    `json:"status"` // 0=待处理, 1=进行中, 2=已暂停, 3=已完成, 4=失败
	CurrentStep string `json:"current_step"`
	Progress    int    `json:"progress"`
	Error       string `json:"error"`
	TargetLang  string `json:"target_lang"`
}

type CreateTaskInput struct {
	InputPath   string `json:"input_path"`
	OutputDir   string `json:"output_dir"`
	Mode        int    `json:"mode"`   // 1=仅字幕, 2=字幕+翻译, 3=字幕+翻译+配音
	Status      int    `json:"status"` // 0=待处理, 1=进行中, 2=已暂停, 3=已完成, 4=失败
	CurrentStep string `json:"current_step"`
	Progress    int    `json:"progress"`
	Error       string `json:"error"`
	TargetLang  string `json:"target_lang"`
}

type GetTaskInput struct {
	ID string `uri:"id"`
}

type DeleteTaskInput struct {
	ID string `uri:"id"`
}
