// Code generated by godddx.
package task

import (
	"github.com/ixugo/goddd/pkg/orm"
	"github.com/ixugo/goddd/pkg/web"
)

type ListTaskLogInput struct {
	web.PagerFilter
	TaskID  string `form:"task_id"`
	Level   string `form:"level"`
	Step    string `form:"step"`
	Message string `form:"message"`
}

func (i *ListTaskLogInput) ToQuery() *orm.Query {
	query := orm.NewQuery(4)
	if i.TaskID != "" {
		query.Where("task_id = ?", i.TaskID)
	}
	if i.Level != "" {
		query.Where("level = ?", i.Level)
	}
	if i.Step != "" {
		query.Where("step = ?", i.Step)
	}
	if i.Message != "" {
		query.Where("message LIKE ?", "%"+i.Message+"%")
	}
	return query.OrderBy("id DESC")
}

type UpdateTaskLogInput struct {
	ID      int64  `uri:"id"`
	TaskID  string `json:"task_id"`
	Level   string `json:"level"`
	Step    string `json:"step"`
	Message string `json:"message"`
}

type CreateTaskLogInput struct {
	TaskID  string `json:"task_id"`
	Level   string `json:"level"`
	Step    string `json:"step"`
	Message string `json:"message"`
}

type GetTaskLogInput struct {
	ID int64 `uri:"id"`
}

type DeleteTaskLogInput struct {
	ID int64 `uri:"id"`
}
