// Code generated by godddx.
package task

import (
	"context"
	"log/slog"

	"github.com/ixugo/goddd/pkg/orm"
	"github.com/ixugo/goddd/pkg/reason"
	"github.com/jinzhu/copier"
	"gorm.io/gorm"
)

// TaskLogStorer Instantiation interface
type TaskLogStorer interface {
	List(context.Context, *[]*TaskLog, orm.Pager, ...orm.QueryOption) (int64, error)
	Get(context.Context, *TaskLog, ...orm.QueryOption) error
	Create(context.Context, *TaskLog) error
	Update(context.Context, *TaskLog, func(*TaskLog), ...orm.QueryOption) error
	Delete(context.Context, *TaskLog, ...orm.QueryOption) error
	Count(context.Context, ...orm.QueryOption) (int64, error)
	Append(context.Context, *TaskLog, int) error
	ListRecent(context.Context, string, int) ([]*TaskLog, error)

	Session(context.Context, ...func(*gorm.DB) error) error
	UpdateWithSession(*gorm.DB, *TaskLog, func(b *TaskLog) error, ...orm.QueryOption) error
}

// ListTaskLog Paginated search
func (c Core) ListTaskLogs(ctx context.Context, in *ListTaskLogInput) ([]*TaskLog, int64, error) {
	query := in.ToQuery()

	items := make([]*TaskLog, 0, in.Limit())
	total, err := c.store.TaskLog().List(ctx, &items, in, query.Encode()...)
	if err != nil {
		return nil, 0, reason.ErrDB.Withf(`List in[%+v] err[%s]`, in, err.Error())
	}
	return items, total, nil
}

// GetTaskLog Query a single object
func (c Core) GetTaskLog(ctx context.Context, id int64) (*TaskLog, error) {
	// 提前赋值是为了缓存
	out := TaskLog{ID: id}
	if err := c.store.TaskLog().Get(ctx, &out, orm.Where("id=?", id)); err != nil {
		if orm.IsErrRecordNotFound(err) {
			return nil, reason.ErrNotFound.Withf(`Get id[%v] err[%s]`, id, err.Error())
		}
		return nil, reason.ErrDB.Withf(`Get id[%v] err[%s]`, id, err.Error())
	}
	return &out, nil
}

// CreateTaskLog Insert into database
func (c Core) CreateTaskLog(ctx context.Context, in *CreateTaskLogInput) (*TaskLog, error) {
	var out TaskLog
	if err := copier.Copy(&out, in); err != nil {
		slog.ErrorContext(ctx, "Copy", "err", err)
	}

	if err := c.store.TaskLog().Create(ctx, &out); err != nil {
		return nil, reason.ErrDB.Withf(`Create err[%s]`, err.Error())
	}
	return &out, nil
}

// UpdateTaskLog Update object information
func (c Core) UpdateTaskLog(ctx context.Context, in *UpdateTaskLogInput, id int64) (*TaskLog, error) {
	var out TaskLog
	if err := c.store.TaskLog().Update(ctx, &out, func(b *TaskLog) {
		if err := copier.Copy(b, in); err != nil {
			slog.ErrorContext(ctx, "Copy", "err", err)
		}
	}, orm.Where("id=?", id)); err != nil {
		return nil, reason.ErrDB.Withf(`Update id[%v] err[%s]`, id, err.Error())
	}
	return &out, nil
}

// DeleteTaskLog Delete object
func (c Core) DeleteTaskLog(ctx context.Context, id int64) (*TaskLog, error) {
	var out TaskLog
	if err := c.store.TaskLog().Delete(ctx, &out, orm.Where("id=?", id)); err != nil {
		return nil, reason.ErrDB.Withf(`Del id[%v] err[%s]`, id, err.Error())
	}
	return &out, nil
}

const maxTaskLogLines = 1000

// AppendTaskLog 持久化单个任务日志，并保证该任务最多保留 1000 行。
func (c Core) AppendTaskLog(ctx context.Context, taskID, level, step, message string) (*TaskLog, error) {
	if level == "" {
		level = "info"
	}
	out := &TaskLog{
		TaskID:  taskID,
		Level:   level,
		Step:    step,
		Message: message,
	}
	if err := c.store.TaskLog().Append(ctx, out, maxTaskLogLines); err != nil {
		return nil, reason.ErrDB.Withf("AppendTaskLog task_id[%s] err[%s]", taskID, err.Error())
	}
	return out, nil
}

// ListRecentTaskLogs 按写入顺序返回指定任务最近的日志。
func (c Core) ListRecentTaskLogs(ctx context.Context, taskID string) ([]*TaskLog, error) {
	items, err := c.store.TaskLog().ListRecent(ctx, taskID, maxTaskLogLines)
	if err != nil {
		return nil, reason.ErrDB.Withf("ListRecentTaskLogs task_id[%s] err[%s]", taskID, err.Error())
	}
	return items, nil
}
