// Code generated by godddx.
package task

import (
	"fmt"
	"time"
)

// TaskLog domain model
type TaskLog struct {
	ID        int64     `gorm:"primaryKey;index:idx_task_logs_task_id_id,priority:2" json:"id"`
	TaskID    string    `gorm:"column:task_id;notNull;default:'';index:idx_task_logs_task_id_id,priority:1" json:"task_id"`
	Level     string    `gorm:"column:level;notNull;default:''" json:"level"`
	Step      string    `gorm:"column:step;notNull;default:''" json:"step"`
	Message   string    `gorm:"column:message;notNull;default:''" json:"message"`
	CreatedAt time.Time `gorm:"column:created_at;notNull;default:CURRENT_TIMESTAMP" json:"created_at"`
}

// TableName database table name
func (*TaskLog) TableName() string {
	return "task_logs"
}

// CacheKey 缓存主键，必须唯一
// godddx 生成缓存代码时，依赖的主键
// 默认应该是 ID 字段，但也可以自定义
func (t *TaskLog) CacheKey() string {
	return fmt.Sprintf("%d", t.ID)
}
