// Code generated by godddx.
package taskcache

import (
	"github.com/ixugo/goddd/pkg/conc"
	"github.com/ixugo/vdub/internal/core/task"
)

var _ task.Storer = (*Cache)(nil)

func NewCache(store task.Storer, cache conc.Cacher) *Cache {
	return &Cache{
		store:   store,
		task:    cache,
		step:    cache,
		taskLog: cache,
	}
}

type Cache struct {
	store   task.Storer
	task    conc.Cacher
	step    conc.Cacher
	taskLog conc.Cacher
}

// Task implements task.TaskStorer
func (c *Cache) Task() task.TaskStorer {
	return (*Task)(c)
}

// Step implements task.StepStorer
func (c *Cache) Step() task.StepStorer {
	return (*Step)(c)
}

// TaskLog implements task.TaskLogStorer
func (c *Cache) TaskLog() task.TaskLogStorer {
	return (*TaskLog)(c)
}
