// Code generated by godddx.
package taskcache

import (
	"context"
	"fmt"

	"github.com/ixugo/goddd/pkg/orm"
	"github.com/ixugo/vdub/internal/core/task"
	"gorm.io/gorm"
)

// 若不需要实现缓存，可以注释
var _ task.StepStorer = (*Step)(nil)

type Step Cache

func (c *Step) cacheKey(key any) string {
	return fmt.Sprintf("STEP:%v", key)
}

// List implements task.StepStorer.
func (c *Step) List(ctx context.Context, bs *[]*task.Step, page orm.Pager, opts ...orm.QueryOption) (int64, error) {
	return c.store.Step().List(ctx, bs, page, opts...)
}

// Get implements task.StepStorer.
// 注意: 若想走缓存，则 model 的 CacheKey 必须实现且必须存在值
// 当 CacheKey 为 id 且出现 orm.Where("id=?",id) 时，查询条件会变成
// SELECT * FROM `users` WHERE `id` = 1 AND `users`.`id` = 1
// 两个值一样则不会受到影响
func (c *Step) Get(ctx context.Context, model *task.Step, opts ...orm.QueryOption) error {
	if model.CacheKey() != "" {
		if err := c.step.Get(ctx, c.cacheKey(model.CacheKey()), model); err == nil {
			return nil
		}
	}
	if err := c.store.Step().Get(ctx, model, opts...); err != nil {
		return err
	}
	c.step.SetNX(ctx, c.cacheKey(model.CacheKey()), model)
	return nil
}

// Create implements task.StepStorer.
func (c *Step) Create(ctx context.Context, model *task.Step) error {
	if err := c.store.Step().Create(ctx, model); err != nil {
		return err
	}
	c.step.Set(ctx, c.cacheKey(model.CacheKey()), model)
	return nil
}

// Update implements task.StepStorer.
func (c *Step) Update(ctx context.Context, model *task.Step, changeFn func(*task.Step), opts ...orm.QueryOption) error {
	if err := c.store.Step().Update(ctx, model, changeFn, opts...); err != nil {
		return err
	}
	c.step.Set(ctx, c.cacheKey(model.CacheKey()), model)
	return nil
}

// Del implements task.StepStorer.
func (c *Step) Delete(ctx context.Context, model *task.Step, opts ...orm.QueryOption) error {
	if err := c.store.Step().Delete(ctx, model, opts...); err != nil {
		return err
	}
	c.step.Del(ctx, c.cacheKey(model.CacheKey()))
	return nil
}

// Count implements task.StepStorer.
func (c *Step) Count(ctx context.Context, opts ...orm.QueryOption) (int64, error) {
	return c.store.Step().Count(ctx, opts...)
}

// Session 事务组合
func (c *Step) Session(ctx context.Context, changeFns ...func(*gorm.DB) error) error {
	// return c.store.Step().Session(ctx, changeFns...)
	return nil
}

// UpdateWithSession 修改事务
func (c *Step) UpdateWithSession(tx *gorm.DB, model *task.Step, changeFn func(b *task.Step) error, opts ...orm.QueryOption) error {
	//	if err := c.store.Step().UpdateWithSession(ctx,model, changeFn,opts...);err!=nil{
	// return err
	//	}
	//	c.step.Set(ctx, c.cacheKey(model.CacheKey() ),  model)
	return nil
}
