// Code generated by godddx.
package taskcache

import (
	"context"
	"fmt"

	"github.com/ixugo/goddd/pkg/orm"
	"github.com/ixugo/vdub/internal/core/task"
	"gorm.io/gorm"
)

// 若不需要实现缓存，可以注释
var _ task.TaskStorer = (*Task)(nil)

type Task Cache

func (c *Task) cacheKey(key any) string {
	return fmt.Sprintf("TASK:%v", key)
}

// List implements task.TaskStorer.
func (c *Task) List(ctx context.Context, bs *[]*task.Task, page orm.Pager, opts ...orm.QueryOption) (int64, error) {
	return c.store.Task().List(ctx, bs, page, opts...)
}

// Get implements task.TaskStorer.
// 注意: 若想走缓存，则 model 的 CacheKey 必须实现且必须存在值
// 当 CacheKey 为 id 且出现 orm.Where("id=?",id) 时，查询条件会变成
// SELECT * FROM `users` WHERE `id` = 1 AND `users`.`id` = 1
// 两个值一样则不会受到影响
func (c *Task) Get(ctx context.Context, model *task.Task, opts ...orm.QueryOption) error {
	if model.CacheKey() != "" {
		if err := c.task.Get(ctx, c.cacheKey(model.CacheKey()), model); err == nil {
			return nil
		}
	}
	if err := c.store.Task().Get(ctx, model, opts...); err != nil {
		return err
	}
	c.task.SetNX(ctx, c.cacheKey(model.CacheKey()), model)
	return nil
}

// Create implements task.TaskStorer.
func (c *Task) Create(ctx context.Context, model *task.Task) error {
	if err := c.store.Task().Create(ctx, model); err != nil {
		return err
	}
	c.task.Set(ctx, c.cacheKey(model.CacheKey()), model)
	return nil
}

// Update implements task.TaskStorer.
func (c *Task) Update(ctx context.Context, model *task.Task, changeFn func(*task.Task), opts ...orm.QueryOption) error {
	if err := c.store.Task().Update(ctx, model, changeFn, opts...); err != nil {
		return err
	}
	c.task.Set(ctx, c.cacheKey(model.CacheKey()), model)
	return nil
}

// Del implements task.TaskStorer.
func (c *Task) Delete(ctx context.Context, model *task.Task, opts ...orm.QueryOption) error {
	if err := c.store.Task().Delete(ctx, model, opts...); err != nil {
		return err
	}
	c.task.Del(ctx, c.cacheKey(model.CacheKey()))
	return nil
}

// Count implements task.TaskStorer.
func (c *Task) Count(ctx context.Context, opts ...orm.QueryOption) (int64, error) {
	return c.store.Task().Count(ctx, opts...)
}

// Session 事务组合
func (c *Task) Session(ctx context.Context, changeFns ...func(*gorm.DB) error) error {
	// return c.store.Task().Session(ctx, changeFns...)
	return nil
}

// UpdateWithSession 修改事务
func (c *Task) UpdateWithSession(tx *gorm.DB, model *task.Task, changeFn func(b *task.Task) error, opts ...orm.QueryOption) error {
	//	if err := c.store.Task().UpdateWithSession(ctx,model, changeFn,opts...);err!=nil{
	// return err
	//	}
	//	c.task.Set(ctx, c.cacheKey(model.CacheKey() ),  model)
	return nil
}
