// Code generated by godddx.
package taskcache

import (
	"context"
	"fmt"

	"github.com/ixugo/goddd/pkg/orm"
	"github.com/ixugo/vdub/internal/core/task"
	"gorm.io/gorm"
)

// 若不需要实现缓存，可以注释
var _ task.TaskLogStorer = (*TaskLog)(nil)

type TaskLog Cache

func (c *TaskLog) cacheKey(key any) string {
	return fmt.Sprintf("TASKLOG:%v", key)
}

// List implements task.TaskLogStorer.
func (c *TaskLog) List(ctx context.Context, bs *[]*task.TaskLog, page orm.Pager, opts ...orm.QueryOption) (int64, error) {
	return c.store.TaskLog().List(ctx, bs, page, opts...)
}

// Get implements task.TaskLogStorer.
// 注意: 若想走缓存，则 model 的 CacheKey 必须实现且必须存在值
// 当 CacheKey 为 id 且出现 orm.Where("id=?",id) 时，查询条件会变成
// SELECT * FROM `users` WHERE `id` = 1 AND `users`.`id` = 1
// 两个值一样则不会受到影响
func (c *TaskLog) Get(ctx context.Context, model *task.TaskLog, opts ...orm.QueryOption) error {
	if model.CacheKey() != "" {
		if err := c.taskLog.Get(ctx, c.cacheKey(model.CacheKey()), model); err == nil {
			return nil
		}
	}
	if err := c.store.TaskLog().Get(ctx, model, opts...); err != nil {
		return err
	}
	c.taskLog.SetNX(ctx, c.cacheKey(model.CacheKey()), model)
	return nil
}

// Create implements task.TaskLogStorer.
func (c *TaskLog) Create(ctx context.Context, model *task.TaskLog) error {
	if err := c.store.TaskLog().Create(ctx, model); err != nil {
		return err
	}
	c.taskLog.Set(ctx, c.cacheKey(model.CacheKey()), model)
	return nil
}

// Update implements task.TaskLogStorer.
func (c *TaskLog) Update(ctx context.Context, model *task.TaskLog, changeFn func(*task.TaskLog), opts ...orm.QueryOption) error {
	if err := c.store.TaskLog().Update(ctx, model, changeFn, opts...); err != nil {
		return err
	}
	c.taskLog.Set(ctx, c.cacheKey(model.CacheKey()), model)
	return nil
}

// Del implements task.TaskLogStorer.
func (c *TaskLog) Delete(ctx context.Context, model *task.TaskLog, opts ...orm.QueryOption) error {
	if err := c.store.TaskLog().Delete(ctx, model, opts...); err != nil {
		return err
	}
	c.taskLog.Del(ctx, c.cacheKey(model.CacheKey()))
	return nil
}

// Count implements task.TaskLogStorer.
func (c *TaskLog) Count(ctx context.Context, opts ...orm.QueryOption) (int64, error) {
	return c.store.TaskLog().Count(ctx, opts...)
}

// Append 直达持久层，任务日志不适合逐行缓存。
func (c *TaskLog) Append(ctx context.Context, model *task.TaskLog, maxLines int) error {
	return c.store.TaskLog().Append(ctx, model, maxLines)
}

// ListRecent 直达持久层，确保顺序与裁剪结果一致。
func (c *TaskLog) ListRecent(ctx context.Context, taskID string, limit int) ([]*task.TaskLog, error) {
	return c.store.TaskLog().ListRecent(ctx, taskID, limit)
}

// Session 事务组合
func (c *TaskLog) Session(ctx context.Context, changeFns ...func(*gorm.DB) error) error {
	return c.store.TaskLog().Session(ctx, changeFns...)
}

// UpdateWithSession 修改事务
func (c *TaskLog) UpdateWithSession(tx *gorm.DB, model *task.TaskLog, changeFn func(b *task.TaskLog) error, opts ...orm.QueryOption) error {
	return c.store.TaskLog().UpdateWithSession(tx, model, changeFn, opts...)
}
