// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"log/slog"
	"net/http"

	"github.com/ixugo/goddd/domain/version/versionapi"
	"github.com/ixugo/vdub/internal/conf"
	"github.com/ixugo/vdub/internal/data"
	"github.com/ixugo/vdub/internal/web/api"
)

// Injectors from wire.go:

func WireApp(bc *conf.Bootstrap, log *slog.Logger) (http.Handler, func(), error) {
	db, err := data.SetupDB(bc)
	if err != nil {
		return nil, nil, err
	}
	core := versionapi.NewVersionCore(db)
	versionapiAPI := versionapi.New(core)
	taskCore := api.NewTaskCore(db)
	scheduler, schedulerCleanup := NewPipelineScheduler(bc, taskCore)
	taskAPI := api.NewTaskAPI(taskCore, scheduler, bc)

	usecase := &api.Usecase{
		Conf:      bc,
		DB:        db,
		Version:   versionapiAPI,
		TaskAPI:   taskAPI,
		Scheduler: scheduler,
	}
	handler := api.NewHTTPHandler(usecase)
	return handler, func() {
		schedulerCleanup()
	}, nil
}
