// Code generated by godddx.
package api

import (
	"os"
	"path/filepath"
	"strings"

	"github.com/gin-gonic/gin"
	"github.com/ixugo/goddd/pkg/orm"
	"github.com/ixugo/goddd/pkg/reason"
	"github.com/ixugo/goddd/pkg/web"
	"github.com/ixugo/vdub/internal/conf"
	"github.com/ixugo/vdub/internal/core/pipeline"
	"github.com/ixugo/vdub/internal/core/task"
	"github.com/ixugo/vdub/internal/core/task/store/taskdb"
	"gorm.io/gorm"
)

// TaskAPI 为 http 提供业务方法
type TaskAPI struct {
	taskCore  task.Core
	scheduler *pipeline.Scheduler
	conf      *conf.Bootstrap
}

func NewTaskCore(db *gorm.DB) task.Core {
	var store task.Storer
	store = taskdb.NewDB(db).AutoMigrate(orm.GetEnabledAutoMigrate())
	// 如果需要缓存，可以取消注释
	// store = taskcache.NewCache(store,conc.NewTTLCache(time.Hour))
	return task.NewCore(store)
}

func NewTaskAPI(core task.Core, sched *pipeline.Scheduler, bc *conf.Bootstrap) TaskAPI {
	return TaskAPI{taskCore: core, scheduler: sched, conf: bc}
}

// NewTaskAPIFromDB 如果已经初始化，可以考虑 NewTaskAPI
// func NewTaskAPIFromDB(db *gorm.DB) TaskAPI {
// 	return NewTaskAPI(NewTaskCore(db))
// }

func RegisterTask(g gin.IRouter, api TaskAPI, handler ...gin.HandlerFunc) {
	{
		group := g.Group("/tasks", handler...)
		group.GET("", web.WrapH(api.listTasks))
		group.POST("", web.WrapH(api.createTask))
		group.POST("/batch", web.WrapH(api.batchCreateTasks))
		group.GET("/:id", web.WrapH(api.getTask))
		group.PUT("/:id", web.WrapH(api.updateTask))
		group.DELETE("/:id", web.WrapH(api.deleteTask))
		group.POST("/:id/pause", web.WrapH(api.pauseTask))
		group.POST("/:id/resume", web.WrapH(api.resumeTask))
	}

	{
		group := g.Group("/steps", handler...)
		group.GET("", web.WrapH(api.listSteps))
		group.GET("/:id", web.WrapH(api.getStep))
		group.PUT("/:id", web.WrapH(api.updateStep))
		group.POST("", web.WrapH(api.createStep))
		group.DELETE("/:id", web.WrapH(api.deleteStep))
	}
}

// >>> task >>>>>>>>>>>>>>>>>>>>

func (a TaskAPI) listTasks(c *gin.Context, in *task.ListTaskInput) (any, error) {
	items, total, err := a.taskCore.ListTasks(c.Request.Context(), in)
	return gin.H{"items": items, "total": total}, err
}

func (a TaskAPI) getTask(c *gin.Context, in *task.GetTaskInput) (*task.Task, error) {
	return a.taskCore.GetTask(c.Request.Context(), in.ID)
}

func (a TaskAPI) updateTask(c *gin.Context, in *task.UpdateTaskInput) (*task.Task, error) {
	return a.taskCore.UpdateTask(c.Request.Context(), in, in.ID)
}

func (a TaskAPI) createTask(c *gin.Context, in *task.CreateTaskInput) (*task.Task, error) {
	if _, err := os.Stat(in.InputPath); err != nil {
		return nil, reason.ErrBadRequest.SetMsg("视频文件不存在")
	}
	if in.Mode < pipeline.ModeSubtitle || in.Mode > pipeline.ModeDub {
		return nil, reason.ErrBadRequest.SetMsg("无效的处理模式")
	}

	if in.OutputDir == "" {
		baseName := strings.TrimSuffix(filepath.Base(in.InputPath), filepath.Ext(in.InputPath))
		in.OutputDir = filepath.Join(filepath.Dir(in.InputPath), baseName+"_vdub")
	}
	if err := os.MkdirAll(in.OutputDir, 0o755); err != nil {
		return nil, reason.ErrServer.Withf("创建输出目录失败: %s", err)
	}
	if in.TargetLang == "" {
		in.TargetLang = a.conf.Pipeline.DefaultTargetLang
	}

	t, err := a.taskCore.CreateTask(c.Request.Context(), in)
	if err != nil {
		return nil, err
	}

	if err := a.scheduler.Submit(pipeline.Job{
		TaskID:     t.ID,
		InputPath:  t.InputPath,
		OutputDir:  t.OutputDir,
		Mode:       t.Mode,
		TargetLang: t.TargetLang,
	}); err != nil {
		return nil, reason.ErrServer.Withf("提交流水线失败: %s", err)
	}

	return t, nil
}

func (a TaskAPI) deleteTask(c *gin.Context, in *task.DeleteTaskInput) (*task.Task, error) {
	return a.taskCore.DeleteTask(c.Request.Context(), in.ID)
}

// pauseTask 暂停正在运行的任务
func (a TaskAPI) pauseTask(_ *gin.Context, in *task.GetTaskInput) (any, error) {
	if !a.scheduler.Pause(in.ID) {
		return nil, reason.ErrBadRequest.SetMsg("任务未在运行中")
	}
	return gin.H{"ok": true}, nil
}

// resumeTask 恢复已暂停或已失败的任务，从上次中断步骤继续
func (a TaskAPI) resumeTask(c *gin.Context, in *task.GetTaskInput) (*task.Task, error) {
	t, err := a.taskCore.GetTask(c.Request.Context(), in.ID)
	if err != nil {
		return nil, err
	}
	if t.Status != 2 && t.Status != 4 {
		return nil, reason.ErrBadRequest.SetMsg("只能恢复已暂停或已失败的任务")
	}
	if a.scheduler.IsRunning(t.ID) {
		return nil, reason.ErrBadRequest.SetMsg("任务已在运行中")
	}

	resumeFrom := t.CurrentStep
	if err := a.taskCore.SetTaskStatus(c.Request.Context(), t.ID, func(b *task.Task) {
		b.Status = 1
		b.Error = ""
	}); err != nil {
		return nil, err
	}

	if err := a.scheduler.Submit(pipeline.Job{
		TaskID:     t.ID,
		InputPath:  t.InputPath,
		OutputDir:  t.OutputDir,
		Mode:       t.Mode,
		TargetLang: t.TargetLang,
		ResumeFrom: resumeFrom,
	}); err != nil {
		return nil, reason.ErrServer.Withf("提交流水线失败: %s", err)
	}

	return a.taskCore.GetTask(c.Request.Context(), t.ID)
}

var videoExts = map[string]bool{
	".mp4": true, ".mkv": true, ".avi": true,
	".mov": true, ".webm": true, ".flv": true, ".wmv": true,
}

type batchCreateInput struct {
	Directory  string `json:"directory" binding:"required"`
	Mode       int    `json:"mode" binding:"required,min=1,max=3"`
	TargetLang string `json:"target_lang"`
}

// batchCreateTasks 扫描目录中的视频文件并批量创建任务
func (a TaskAPI) batchCreateTasks(c *gin.Context, in *batchCreateInput) (any, error) {
	entries, err := os.ReadDir(in.Directory)
	if err != nil {
		return nil, reason.ErrBadRequest.SetMsg("无法读取目录")
	}
	if in.TargetLang == "" {
		in.TargetLang = a.conf.Pipeline.DefaultTargetLang
	}

	var tasks []*task.Task
	for _, entry := range entries {
		if entry.IsDir() {
			continue
		}
		ext := strings.ToLower(filepath.Ext(entry.Name()))
		if !videoExts[ext] {
			continue
		}

		inputPath := filepath.Join(in.Directory, entry.Name())
		baseName := strings.TrimSuffix(entry.Name(), filepath.Ext(entry.Name()))
		outputDir := filepath.Join(in.Directory, baseName+"_vdub")
		if err := os.MkdirAll(outputDir, 0o755); err != nil {
			continue
		}

		t, err := a.taskCore.CreateTask(c.Request.Context(), &task.CreateTaskInput{
			InputPath:  inputPath,
			OutputDir:  outputDir,
			Mode:       in.Mode,
			TargetLang: in.TargetLang,
		})
		if err != nil {
			continue
		}

		_ = a.scheduler.Submit(pipeline.Job{
			TaskID:     t.ID,
			InputPath:  t.InputPath,
			OutputDir:  t.OutputDir,
			Mode:       t.Mode,
			TargetLang: t.TargetLang,
		})
		tasks = append(tasks, t)
	}

	return gin.H{"items": tasks, "total": len(tasks)}, nil
}

// >>> step >>>>>>>>>>>>>>>>>>>>

func (a TaskAPI) listSteps(c *gin.Context, in *task.ListStepInput) (any, error) {
	items, total, err := a.taskCore.ListSteps(c.Request.Context(), in)
	return gin.H{"items": items, "total": total}, err
}

func (a TaskAPI) getStep(c *gin.Context, in *task.GetStepInput) (*task.Step, error) {
	return a.taskCore.GetStep(c.Request.Context(), in.ID)
}

func (a TaskAPI) updateStep(c *gin.Context, in *task.UpdateStepInput) (*task.Step, error) {
	return a.taskCore.UpdateStep(c.Request.Context(), in, in.ID)
}

func (a TaskAPI) createStep(c *gin.Context, in *task.CreateStepInput) (*task.Step, error) {
	return a.taskCore.CreateStep(c.Request.Context(), in)
}

func (a TaskAPI) deleteStep(c *gin.Context, in *task.DeleteStepInput) (*task.Step, error) {
	return a.taskCore.DeleteStep(c.Request.Context(), in.ID)
}
