// Code generated by godddx.
package api

import (
	"github.com/gin-gonic/gin"
	"github.com/ixugo/goddd/pkg/orm"
	"github.com/ixugo/goddd/pkg/web"
	"github.com/ixugo/vdub/internal/core/task"
	"github.com/ixugo/vdub/internal/core/task/store/taskdb"
	"gorm.io/gorm"
)

// TaskAPI 为 http 提供业务方法
type TaskAPI struct {
	taskCore task.Core
}

func NewTaskCore(db *gorm.DB) task.Core {
	var store task.Storer
	store = taskdb.NewDB(db).AutoMigrate(orm.GetEnabledAutoMigrate())
	// 如果需要缓存，可以取消注释
	// store = taskcache.NewCache(store,conc.NewTTLCache(time.Hour))
	return task.NewCore(store)
}

func NewTaskAPI(core task.Core) TaskAPI {
	return TaskAPI{taskCore: core}
}

// NewTaskAPIFromDB 如果已经初始化，可以考虑 NewTaskAPI
// func NewTaskAPIFromDB(db *gorm.DB) TaskAPI {
// 	return NewTaskAPI(NewTaskCore(db))
// }

func RegisterTask(g gin.IRouter, api TaskAPI, handler ...gin.HandlerFunc) {
	{
		group := g.Group("/tasks", handler...)
		group.GET("", web.WrapH(api.listTasks))
		group.GET("/:id", web.WrapH(api.getTask))
		group.PUT("/:id", web.WrapH(api.updateTask))
		group.POST("", web.WrapH(api.createTask))
		group.DELETE("/:id", web.WrapH(api.deleteTask))
	}

	{
		group := g.Group("/steps", handler...)
		group.GET("", web.WrapH(api.listSteps))
		group.GET("/:id", web.WrapH(api.getStep))
		group.PUT("/:id", web.WrapH(api.updateStep))
		group.POST("", web.WrapH(api.createStep))
		group.DELETE("/:id", web.WrapH(api.deleteStep))
	}
}

// >>> task >>>>>>>>>>>>>>>>>>>>

func (a TaskAPI) listTasks(c *gin.Context, in *task.ListTaskInput) (any, error) {
	items, total, err := a.taskCore.ListTasks(c.Request.Context(), in)
	return gin.H{"items": items, "total": total}, err
}

func (a TaskAPI) getTask(c *gin.Context, in *task.GetTaskInput) (*task.Task, error) {
	return a.taskCore.GetTask(c.Request.Context(), in.ID)
}

func (a TaskAPI) updateTask(c *gin.Context, in *task.UpdateTaskInput) (*task.Task, error) {
	return a.taskCore.UpdateTask(c.Request.Context(), in, in.ID)
}

func (a TaskAPI) createTask(c *gin.Context, in *task.CreateTaskInput) (*task.Task, error) {
	return a.taskCore.CreateTask(c.Request.Context(), in)
}

func (a TaskAPI) deleteTask(c *gin.Context, in *task.DeleteTaskInput) (*task.Task, error) {
	return a.taskCore.DeleteTask(c.Request.Context(), in.ID)
}

// >>> step >>>>>>>>>>>>>>>>>>>>

func (a TaskAPI) listSteps(c *gin.Context, in *task.ListStepInput) (any, error) {
	items, total, err := a.taskCore.ListSteps(c.Request.Context(), in)
	return gin.H{"items": items, "total": total}, err
}

func (a TaskAPI) getStep(c *gin.Context, in *task.GetStepInput) (*task.Step, error) {
	return a.taskCore.GetStep(c.Request.Context(), in.ID)
}

func (a TaskAPI) updateStep(c *gin.Context, in *task.UpdateStepInput) (*task.Step, error) {
	return a.taskCore.UpdateStep(c.Request.Context(), in, in.ID)
}

func (a TaskAPI) createStep(c *gin.Context, in *task.CreateStepInput) (*task.Step, error) {
	return a.taskCore.CreateStep(c.Request.Context(), in)
}

func (a TaskAPI) deleteStep(c *gin.Context, in *task.DeleteStepInput) (*task.Step, error) {
	return a.taskCore.DeleteStep(c.Request.Context(), in.ID)
}
